export const ICONS = {
	EyeHide: require('@assets/icons/eye-hide.svg'),
	Unlock: require('@assets/icons/unlock.svg'),
	Mail: require('@assets/icons/mail.svg'),
	Tick: require('@assets/icons/tick.svg'),
	Untick: require('@assets/icons/untick.svg'),
	RadioCheck: require('@assets/icons/radio-check.svg'),
	RadioUncheck: require('@assets/icons/radio-uncheck.svg'),
	Facebook: require('@assets/icons/facebook.svg'),
	Twitter: require('@assets/icons/twitter.svg'),
	Google: require('@assets/icons/google.svg'),
	ArrowLeft: require('@assets/icons/arrow-left.svg'),
	SMS: require('@assets/icons/sms.svg'),
	Envelope: require('@assets/icons/envelope.svg'),
	User: require('@assets/icons/user.svg'),
	Phone: require('@assets/icons/phone.svg'),
	Address: require('@assets/icons/address.svg'),
	School: require('@assets/icons/school.svg'),
	Calendar: require('@assets/icons/calendar.svg'),
	Close: require('@assets/icons/close.svg'),
	Add: require('@assets/icons/add.svg'),
}
